[project]
name = "aquaculture-fishbase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.0.0",
    "duckdb>=1.3.2",
    "hf-xet>=1.1.9",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "polars>=1.33.0",
]
